renewing test scripts: Now it not only gives the missing lemma, but also generates them. Note: Changed +V+Inf to +V+Ger.
git-svn-id: https://gtsvn.uit.no/langtech/trunk/langs/yrk@108368 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

diff --git a/test/src/morphology/generate-verb-lemmas.sh.in b/test/src/morphology/generate-verb-lemmas.sh.in
--- a/test/src/morphology/generate-verb-lemmas.sh.in
+++ b/test/src/morphology/generate-verb-lemmas.sh.in
@@ -7,22 +7,33 @@
 # - an exit status of 99 a hard error
 # - any other exit status will denote a failure.
 
+# To run this test script only, do:
+#
+# make check TESTS=generate-adjective-lemmas.sh
 
-# Test that all verb lemmas do generate as themselves:
+# This test script will test that all noun lemmas do generate as themselves.
+# Extend as needed, and copy to new files to adapt to other parts of speech.
+# The changes usually needed are:
+#
+# 1. change the reference to the source file (line 23)
+# 2. extend the extract lemmas egrep expression (lines 53 ff)
+# 3. adapt the tag addition and lemma generation instructions (lines 79 ff)
 
 
 ###### Variables: #######
-sourcefile=${srcdir}/../../../src/morphology/stems/verbs.lexc
-lemmas=./verbs.txt
-generatedlemmas=./gen-verbs
-failedlemmas=./fail-verb-lemmas
-generatorfile=./../../../src/generator-gt-norm
-resultfile=lemma-gen-verb-diff
+### in ###
+source_file=${srcdir}/../../../src/morphology/stems/verbs.lexc
+generator_file=./../../../src/generator-gt-norm
+
+### out ###
+lemmas=./filtered-verbs
+generated_lemmas=./generated-verbs
+result_file=${srcdir}/missing_verb_lemmas.txt
 
 # FAIL if source file does not exist:
-if [ ! -f $sourcefile ]; then
+if [ ! -f $source_file ]; then
     echo
-    echo "*** Warning: Source file $sourcefile not found."
+    echo "*** Warning: Source file $source_file not found."
     echo
     exit 77
 fi
@@ -43,8 +54,12 @@ fi
 EXTEDITOR=@SEE@
 
 ###### Extraction: #######
-@GTCORE@/scripts/extract-lemmas.sh \
-	$sourcefile "(CmpN/Last)" > $lemmas
+
+grep ";" $source_file | \
+  egrep -v "^(\!|\@|<)" | \
+  sed 's/% /€/g' | sed 's/%:/¢/g' |  tr ":+" " " | cut -d " " -f1 | \
+  tr -d "%" | tr "€" " " | tr "¢" ":" | grep -v '^ei$' | sort -u > $lemmas
+  
 
 ###### Start testing: #######
 transducer_found=0
@@ -64,47 +79,30 @@ for f in $fsttype; do
 	    echo "$f - FAIL"
 	    continue
 	fi
-	if [ -f "$generatorfile.$suffix" ]; then
+	if [ -f "$generator_file.$suffix" ]; then
 		let "transducer_found += 1"
 
-###### Test non-compounds: #######
-		# generate Intransitive Gerund:
-		sed 's/$/+V+IV+Ger/' $lemmas | $lookuptool $generatorfile.$suffix \
-			| cut -f2  > $generatedlemmas.$f.tmp.txt
-		fgrep -v "+V+" $generatedlemmas.$f.tmp.txt | grep -v "^$" \
-			| sort -u >> $generatedlemmas.$f.txt
-		fgrep    "+V+" $generatedlemmas.$f.tmp.txt | cut -d'+' -f1 \
-			| sort -u  > $failedlemmas.$f.txt
-		# generate Transitive Gerund:
-		sed 's/$/+V+TV+Ger/' $failedlemmas.$f.txt \
-			| $lookuptool $generatorfile.$suffix \
-			| cut -f2  > $generatedlemmas.$f.tmp.txt
-		fgrep -v "+V+" $generatedlemmas.$f.tmp.txt | grep -v "^$" \
-			| sort -u >> $generatedlemmas.$f.txt
-		fgrep    "+V+" $generatedlemmas.$f.tmp.txt | cut -d'+' -f1 \
-			| sort -u  > $failedlemmas.$f.txt
-		# generate Reflexive Gerund:
-		sed 's/$/+V+Refl+Ger/' $failedlemmas.$f.txt \
-			| $lookuptool $generatorfile.$suffix \
-			| cut -f2  > $generatedlemmas.$f.tmp.txt
-		fgrep -v "+V+" $generatedlemmas.$f.tmp.txt | grep -v "^$" \
-			| sort -u >> $generatedlemmas.$f.txt
-		fgrep    "+V+" $generatedlemmas.$f.tmp.txt | cut -d'+' -f1 \
-			| sort -u  > $failedlemmas.$f.txt
+###### Generate the infinitives: #######
 
-###### Collect results: #######
-		# Sort and compare original input with resulting output - the diff is
-		# stored and opened in SEE:
-		sort -u -o $generatedlemmas.$f.txt $generatedlemmas.$f.txt 
-		comm -23 $lemmas $generatedlemmas.$f.txt | rev | sort | rev \
-		> $resultfile.$f.txt
+        sed 's/$/+V+Ger/' $lemmas | \
+        		$lookuptool $generator_file.$suffix | \
+          cut -f2 | grep -v "V+" | grep -v "^$" | sort -u > $generated_lemmas.$f.txt		
+				
+# Sorter, unifiser
+		sort -u -o $lemmas $lemmas 
+		sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt 
 
-		# if at least one word is found, the test failed, and the list of failed
-		# lemmas is opened in SubEthaEdit:
-		if [ -s $resultfile.$f.txt ]; then
+# Sammenlikne: Former som er i lemmalista med ikke i lista med genererte former,
+# lagre i missingverbLemmas.txt. Formene generes med  +V+Ger for enklere debugging.
+		comm -23 $lemmas $generated_lemmas.$f.txt |\
+		  grep -v '^$' | sed 's/$/+V+Ger/' |\
+		  $lookuptool $generator_file.$suffix > $result_file.$f.txt
+
+		# Open the diff file in SubEthaEdit (if there is a diff):
+		if [ -s $result_file.$f.txt ]; then
 			# Only open the failed lemmas in see if @SEE@ is defined:
 			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $resultfile.$f.txt
+				$EXTEDITOR $result_file.$f.txt
 			fi
 		    Fail=1
 		    echo "$f - FAIL"
@@ -113,6 +111,8 @@ for f in $fsttype; do
 	    echo "$f - PASS"
 	fi
 done
+
+
 
 # When done, remove the generated data file:
 rm -f $lemmas
@@ -124,5 +124,5 @@ fi
 
 if [ $transducer_found -eq 0 ]; then
     echo ERROR: No transducer found
-    exit 77
+    exit 1
 fi
