Now testing for ordinary, reflexive and auxiliary verbs, and listing  missing lemmas.
git-svn-id: https://gtsvn.uit.no/langtech/trunk/langs/yrk@168426 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

diff --git a/test/src/morphology/generate-verb-lemmas.sh.in b/test/src/morphology/generate-verb-lemmas.sh.in
--- a/test/src/morphology/generate-verb-lemmas.sh.in
+++ b/test/src/morphology/generate-verb-lemmas.sh.in
@@ -9,7 +9,7 @@
 
 # To run this test script only, do:
 #
-# make check TESTS=generate-adjective-lemmas.sh
+# make check TESTS=generate-noun-lemmas.sh
 
 # This test script will test that all noun lemmas do generate as themselves.
 # Extend as needed, and copy to new files to adapt to other parts of speech.
@@ -19,16 +19,19 @@
 # 2. extend the extract lemmas egrep expression (lines 53 ff)
 # 3. adapt the tag addition and lemma generation instructions (lines 79 ff)
 
-
 ###### Variables: #######
+POS=verbs
 ### in ###
-source_file=${srcdir}/../../../src/morphology/stems/verbs.lexc
+source_file=${srcdir}/../../../src/morphology/stems/${POS}.lexc
 generator_file=./../../../src/generator-gt-norm
+analyser_file=./../../../src/analyser-gt-norm
 
 ### out ###
-lemmas=./filtered-verbs
-generated_lemmas=./generated-verbs
-result_file=${srcdir}/missing_verb_lemmas.txt
+lemmas=./filtered-${POS}
+generated_lemmas=./generated-${POS}
+result_file=missing_${POS}_lemmas
+ana_result_file=analysed_missing_${POS}_lemmas
+gen_result_file=generated_missing_${POS}_lemmas
 
 # SKIP if source file does not exist (works with both single and
 # multiple files):
@@ -54,13 +57,12 @@ fi
 # Get external Mac editor for viewing failed results from configure:
 EXTEDITOR=@SEE@
 
-###### Extraction: #######
-
-grep ";" $source_file | \
-  egrep -v "^(\!|\@|<)" | \
-  sed 's/% /€/g' | sed 's/%:/¢/g' |  tr ":+" " " | cut -d " " -f1 | \
-  tr -d "%" | tr "€" " " | tr "¢" ":" | grep -v '^ei$' | sort -u > $lemmas
-  
+##### Extract lemmas - add additional egrep pattern as parameters: #####
+##### --include "(pattern1|pattern2|...)"                          #####
+##### --exclude "(pattern1|pattern2|...)"                          #####
+@GTCORE@/scripts/extract-lemmas.sh \
+    --exclude "( NEG | LEA )" \
+    $source_file > $lemmas
 
 ###### Start testing: #######
 transducer_found=0
@@ -89,44 +91,72 @@ for f in $fsttype; do
     if [ -f "$generator_file.$suffix" ]; then
         let "transducer_found += 1"
 
-###### Generate the infinitives: #######
+###### Test verbs: #######
+        # generate verbs in gerund, extract the resulting generated lemma,
+        # store it:
+        sed 's/$/+V+Ger/' $lemmas | $lookup_tool $generator_file.$suffix \
+            | fgrep -v "+?" | grep -v "^$" | cut -f2 | sort -u \
+            > $generated_lemmas.$f.txt 
+        # generate reflexive verbs in gerund, extract the resulting generated lemma,
+        # store it:
+        sed 's/$/+V+Ger/' $lemmas | $lookup_tool $generator_file.$suffix \
+            | fgrep "+?" | cut -d "+" -f1 | sed 's/$/+V+Refl+Ger/' \
+	    | $lookup_tool $generator_file.$suffix | fgrep -v "+?" | cut -f2 \
+            | grep -v "^$" >> $generated_lemmas.$f.txt 
+        # generate auxiliary verbs in gerund, extract the resulting generated lemma,
+        # store it:
+        sed 's/$/+V+Ger/' $lemmas | $lookup_tool $generator_file.$suffix \
+            | fgrep "+?" | cut -d "+" -f1 | sed 's/$/+V+Refl+Ger/' \
+	    | $lookup_tool $generator_file.$suffix | fgrep -v "+?" | cut -f2 \
+            | fgrep "+?" | cut -d "+" -f1 | sed 's/$/+V+Aux+Ger/' \
+	    | $lookup_tool $generator_file.$suffix | fgrep -v "+?" | cut -f2 \
+            | grep -v "^$" >> $generated_lemmas.$f.txt 
 
-        sed 's/$/+V+Ger/' $lemmas | \
-        		$lookup_tool $generator_file.$suffix | \
-          cut -f2 | grep -v "V+" | grep -v "^$" | sort -u > $generated_lemmas.$f.txt		
-				
-# Sorter, unifiser
-		sort -u -o $lemmas $lemmas 
-		sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt 
+###### Collect results, and generate debug info if FAIL: #######
+        # Sort and compare original input with resulting output - the diff is
+        # used to generate lemmas which are opened in SEE:
+        sort -u -o $generated_lemmas.$f.txt $generated_lemmas.$f.txt 
+        comm -23 $lemmas $generated_lemmas.$f.txt > $result_file.$f.txt
 
-# Sammenlikne: Former som er i lemmalista med ikke i lista med genererte former,
-# lagre i missingverbLemmas.txt. Formene generes med  +V+Ger for enklere debugging.
-		comm -23 $lemmas $generated_lemmas.$f.txt |\
-		  grep -v '^$' | sed 's/$/+V+Ger/' |\
-		  $lookup_tool $generator_file.$suffix > $result_file.$f.txt
-
-		# Open the diff file in SubEthaEdit (if there is a diff):
-		if [ -s $result_file.$f.txt ]; then
-			# Only open the failed lemmas in see if @SEE@ is defined:
-			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $result_file.$f.txt
-			fi
-		    Fail=1
-		    echo "$f - FAIL"
-		    continue
-		fi
-	    echo "$f - PASS"
-	fi
+        # Open the diff file in SubEthaEdit (if there is a diff):
+        if [ -s $result_file.$f.txt ]; then
+            grep -v '^$' $result_file.$f.txt \
+              | sed 's/$/+V+Ger/' \
+              | $lookup_tool $generator_file.$suffix \
+              > $gen_result_file.$f.txt
+            # If we have an analyser, analyse the missing lemmas as well:
+            if test -e $analyser_file.$suffix ; then
+                grep -v '^$' $result_file.$f.txt \
+                  | $lookup_tool $analyser_file.$suffix \
+                  > $ana_result_file.$f.txt
+            fi
+            # Only open the failed lemmas in see if @SEE@ is defined:
+            if [ "$EXTEDITOR" ]; then
+#                $EXTEDITOR $result_file.$f.txt
+#                $EXTEDITOR $gen_result_file.$f.txt
+                $EXTEDITOR $ana_result_file.$f.txt
+            else
+                echo "There where problem lemmas. Details in:"
+                echo "* $result_file.$f.txt    "
+                echo "* $gen_result_file.$f.txt"
+                echo "* $ana_result_file.$f.txt"
+            fi
+            Fail=1
+            echo "$f - FAIL"
+            continue
+        fi
+        echo "$f - PASS"
+    fi
 done
 
 # At least one of the Xerox or HFST tests failed:
 if [ "$Fail" = "1" ]; then
-	exit 1
+    exit 1
 fi
 
 if [ $transducer_found -eq 0 ]; then
     echo ERROR: No transducer found
-    exit 1
+    exit 77
 fi
 
 # When done, remove the generated data file:
